#include "hal_data.h"

#define TRANSFER_LENGTH			(16)

uint8_t  g_dest[TRANSFER_LENGTH];
uint8_t  g_src[TRANSFER_LENGTH];
uint8_t  g_out_of_band_received[TRANSFER_LENGTH];
volatile uint32_t g_transfer_complete = 0;
volatile uint32_t g_receive_complete  = 0;
volatile uint32_t g_out_of_band_index = 0;

void uart_callback (uart_callback_args_t * p_args)
{
	/* Handle the UART event */
	switch (p_args->event) {
	/* Received a character */
	case UART_EVENT_RX_CHAR:
		/* Only put the next character in the receive buffer if there is space for it */
		if (sizeof(g_out_of_band_received) > g_out_of_band_index) {
			g_out_of_band_received[g_out_of_band_index++] = (uint8_t) p_args->data;
		}
		break;
	/* Receive complete */
	case UART_EVENT_RX_COMPLETE:
		g_receive_complete = 1;
		break;
	/* Transmit complete */
	case UART_EVENT_TX_COMPLETE:
		g_transfer_complete = 1;
		break;
	default:
		break;
	}
}

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
	bsp_io_level_t level_w = BSP_IO_LEVEL_HIGH;

	/* Initialize p_src to known data */
	for (uint32_t i = 0; i < TRANSFER_LENGTH; i++) {
		g_src[i] = (uint8_t) ('A' + (i % 26));
	}

	/* Open the transfer instance with initial configuration. */
	fsp_err_t err = R_SCI_UART_Open(&g_uart0_ctrl, &g_uart0_cfg);
	assert(FSP_SUCCESS == err);

	/* Call the R_IOPORT_PinCfg if the configuration was not part of initial configurations made in open */
	err = R_IOPORT_PinCfg(&g_ioport_ctrl, BSP_IO_PORT_00_PIN_12, IOPORT_CFG_PORT_DIRECTION_OUTPUT);
	assert(FSP_SUCCESS == err);

	while (1) {
		err = R_SCI_UART_Read(&g_uart0_ctrl, g_dest, TRANSFER_LENGTH);
		assert(FSP_SUCCESS == err);
		err = R_SCI_UART_Write(&g_uart0_ctrl, g_src, TRANSFER_LENGTH);
		assert(FSP_SUCCESS == err);

		while (!g_transfer_complete) {
		}
		g_transfer_complete = 0;

//		while (!g_receive_complete) {
//		}
		g_receive_complete = 0;
		g_out_of_band_index = 0;

		/* Update LED on RA4M1_64Pin_CoreBoard */
		err = R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_00_PIN_12, level_w);
		assert(FSP_SUCCESS == err);
		level_w = !level_w;

		/* Delay 1000ms */
		R_BSP_SoftwareDelay(1000, BSP_DELAY_UNITS_MILLISECONDS); // NOLINT
	}
}

