#include "hal_data.h"

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
	fsp_err_t err;

	/* Initialize the IOPORT module and configure the pins */
	err = R_IOPORT_Open(&g_ioport_ctrl, &g_bsp_pin_cfg);
	/* Handle any errors. This function should be defined by the user. */
	assert(FSP_SUCCESS == err);

	/* Configure Pin as output
	* Call the R_IOPORT_PinCfg if the configuration was not part of initial configurations made in open */
	err = R_IOPORT_PinCfg(&g_ioport_ctrl, BSP_IO_PORT_00_PIN_12, IOPORT_CFG_PORT_DIRECTION_OUTPUT);
	assert(FSP_SUCCESS == err);

	bsp_io_level_t level = BSP_IO_LEVEL_LOW;
	while (1) {
		/* Determine the next state of the LEDs */
		if (BSP_IO_LEVEL_LOW == level) {
			level = BSP_IO_LEVEL_HIGH;
		}
		else {
			level = BSP_IO_LEVEL_LOW;
		}
		/* Update LED on RA6M3-PK */
		err = R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_00_PIN_12, level);
		assert(FSP_SUCCESS == err);

		/* Delay */
		R_BSP_SoftwareDelay(100, BSP_DELAY_UNITS_MILLISECONDS); // NOLINT
	}
}

