#include "hal_data.h"

volatile uint8_t g_external_irq_complete = 0;

/* Called from icu_irq_isr */
void irq_callback (external_irq_callback_args_t * p_args)
{
    (void) p_args;
    g_external_irq_complete = 1;
}
/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
	/* Configure the external interrupt. */
	fsp_err_t err = R_ICU_ExternalIrqOpen(&g_external_irq0_ctrl, &g_external_irq0_cfg);
	assert(FSP_SUCCESS == err);

	/* Enable the external interrupt. */
	/* Enable not required when used with ELC or DMAC. */
	err = R_ICU_ExternalIrqEnable(&g_external_irq0_ctrl);
	assert(FSP_SUCCESS == err);

	while (1) {
		while (0 == g_external_irq_complete)
		{
			/* Wait for interrupt. */
		}
		g_external_irq_complete = 0;

		/* Update LED on RA4M1_64Pin_CoreBoard */
		R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_00_PIN_12, BSP_IO_LEVEL_HIGH);
		/* Delay 1000ms */
		R_BSP_SoftwareDelay(1000, BSP_DELAY_UNITS_MILLISECONDS);
		/* Update LED on RA4M1_64Pin_CoreBoard */
		R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_00_PIN_12, BSP_IO_LEVEL_LOW);
	}
}

