#include "hal_data.h"

/* IRQ番号の割り当て */
#define IRQ_PORT_IRQ0		(0)									// 外部端子(IRQ0)割り込み

volatile uint8_t g_external_irq_complete = 0;

/* PORT_IRQ0 割り込みハンドラ */
void PORT_IRQ0_Handler(void)
{
    /* 割り込み要求フラグ クリア */
	R_ICU->IELSR_b[IRQ_PORT_IRQ0].IR = 0;

    g_external_irq_complete = 1;
}

/* PORT_IRQ0 初期化 */
static void port_irq0_init(void)
{
	/* ---- PORT_IRQ0 無効 ---- */
	R_ICU->IELSR[IRQ_PORT_IRQ0] = 0x00000000;
	R_ICU->IRQCR[0] = 0x00;

	/* ---- PORT_IRQ0 設定 ---- */
	R_ICU->IRQCR_b[0].IRQMD = 0;								// 立ち下がりエッジ
	R_ICU->IRQCR_b[0].FCLKSEL = 3;								// PCLKB/64
	R_ICU->IRQCR_b[0].FLTEN = 1;								// デジタルフィルタ有効

	/* ---- ICU → NVIC 割り込み割り当て ---- */
	R_ICU->IELSR_b[IRQ_PORT_IRQ0].IR = 0;						// 割り込み要求フラグ クリア
	R_ICU->IELSR_b[IRQ_PORT_IRQ0].IELS = ELC_EVENT_ICU_IRQ0;	// PORT_IRQ0

	/* ---- NVIC 設定 ---- */
	NVIC_ClearPendingIRQ((IRQn_Type)IRQ_PORT_IRQ0);
	NVIC_SetPriority((IRQn_Type)IRQ_PORT_IRQ0, 12);				// 優先度 12
	NVIC_EnableIRQ((IRQn_Type)IRQ_PORT_IRQ0);
}

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
	/* PORT_IRQ0 初期化 */
	port_irq0_init();

	while (1) {
		while (0 == g_external_irq_complete)
		{
			/* Wait for interrupt. */
		}
		g_external_irq_complete = 0;

		/* Update LED on RA4M1_64Pin_CoreBoard */
		R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_00_PIN_12, BSP_IO_LEVEL_HIGH);
		/* Delay 1000ms */
		R_BSP_SoftwareDelay(1000, BSP_DELAY_UNITS_MILLISECONDS);
		/* Update LED on RA4M1_64Pin_CoreBoard */
		R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_00_PIN_12, BSP_IO_LEVEL_LOW);
	}
}

